#!/usr/bin/env bash
# This script pings an IP address 5 times to check if a host is on the network

# Check if no argument is passed
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the first argument
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
